databases:
  - name: railstodo
    databaseName: railstodo_production
    user: todouser
    plan: free

services:
  - type: web
    name: railstodo-web
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: railstodo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
